### ISSUE TITLE
Create configuration file format & parser.

### ISSUE THREAD

**Issue by albinohat** [TranscranialOrchestra/BitCollector#3]
Create the configuration parser based on the format chosen. Blocked by issue #2.

**Comment by wywin** [comment]
Might I suggest [ConfigParser](https://docs.python.org/2/library/configparser.html)?

**Comment by albinohat** [comment]
I looked into it. It is meant to be used with INI files. I have code written to parse JSON in other projects. I'll be repurposing that. Been busy with cater fair and such all week. Will likely do it in lab. I want the framework done this weekend so everyone else can get started.
